import { Resource } from "i18next";

export const resources: Resource = {
  en: {
    translation: {
      // Navigation
      "Navigation Toggle": "Toggle navigation menu",
      "Navigation Overview": "Overview",
      "Navigation Tickets": "Tickets",
      "Navigation Create Ticket": "Create Ticket",
      "Navigation Ideas": "Ideas",
      "Navigation Contacts": "Contacts",
      "Navigation Agents": "Agents",
      "Navigation Articles": "Articles",
      "Navigation Settings": "Settings",
      "Navigation Subscription": "Subscription",
      // Header
      "Header My Account": "My Account",
      "Header Logout": "Logout",
      // Overview
      "Total Unresolved": "Unresolved",
      "Total Overdue": "Overdue",
      "Total Open": "Open",
      "Total On Hold": "On Hold",
      "Chart Title": "Today's trends",
      "Chart Desc": "as of",
      "Chart Today": "Today",
      "Chart Yesterday": "Yesterday",
      "Statistic Resolved": "Resolved",
      "Statistic Received": "Received",
      "Statistic Avg First Response": "Average first response time",
      "Statistic Avg Response": "Average response time",
      "Statistic Resolution": "Resolution within SLA",
      "Unresolved Title": "Unresolved tickets",
      "Unresolved Detail": "View details",
      "Unresolved Feature Request": "Waiting on Feature Request",
      "Unresolved Cust Response": "Awaiting Customer Response",
      "Unresolved Developer Fix": "Awaiting Developer Fix",
      "Unresolved Pending": "Pending",
      "Tasks Title": "Tasks",
      "Tasks Desc": "Today",
      "Tasks Detail": "View all",
      "Tasks Create": "Create new task",
      // Tickets
      "Ticket Title": "All tickets",
      "Ticket TH Ticket Detail": "Ticket detail",
      "Ticket TH Cust Name": "Customer Name",
      "Ticket TH Date": "Date",
      "Ticket TH Priority": "Priority",
      "Ticket TD Sub 1": "Updated",
      "Ticket TD Sub 2": "on",
      "Ticket TD Action 1": "Approve ticket",
      "Ticket TD Action 2": "Reject ticket",
      // Settings
      "Settings Theme": "Theme",
      "Theme Light": "Light",
      "Theme Dark": "Dark",
      "Theme System": "System",
      "Settings Language": "Language",
      // Table
      "Table Rows Per Page": "Rows per page",
      "Table Of": "of",
      "Table Prev": "Go to previous page",
      "Table Next": "Go to next page",
      "Table Sort": "Sort",
      "Table Sort Oldest": "Oldest",
      "Table Sort Latest": "Latest",
      // Notification
      "Notification Title": "Notification",
      // Search box
      "Search Placeholder": "Search",
      "Search Not Found": "No task found",
      // Login
      "Login Card Title": "Log In to Dashboard Kit",
      "Login Card Desc": "Enter your email and password below",
      "Login Form Email": "Email Address",
      "Login Form Pass": "Password",
      "Login Form Forgot Pass": "Forgot password?",
      "Login Register 1": "Don't have an account?",
      "Login Register 2": "Sign up",
      // Create ticket
      "Ticket Form Title": "Title",
      "Ticket Form Priority": "Priority",
      "Ticket Form Button": "Create new ticket",
    },
  },
  id: {
    translation: {
      // Sidebar
      "Navigation Toggle": "Buka menu navigasi",
      "Navigation Overview": "Ringkasan",
      "Navigation Tickets": "Tiket",
      "Navigation Create Ticket": "Buat Tiket",
      "Navigation Ideas": "Ide",
      "Navigation Contacts": "Kontak",
      "Navigation Agents": "Agen",
      "Navigation Articles": "Artikel",
      "Navigation Settings": "Pengaturan",
      "Navigation Subscription": "Berlangganan",
      // Header
      "Header My Account": "Akun saya",
      "Header Logout": "Keluar",
      // Overview
      "Total Unresolved": "Belum terselesaikan",
      "Total Overdue": "Terlambat",
      "Total Open": "Buka",
      "Total On Hold": "Tertahan",
      "Chart Title": "Tren saat ini",
      "Chart Desc": "per",
      "Chart Today": "Hari ini",
      "Chart Yesterday": "Kemarin",
      "Statistic Resolved": "Terselesaikan",
      "Statistic Received": "Diterima",
      "Statistic Avg First Response": "Rata-rata waktu respons pertama",
      "Statistic Avg Response": "Waktu respons rata-rata",
      "Statistic Resolution": "Resolusi dalam SLA",
      "Unresolved Title": "Tiket yang belum terselesaikan",
      "Unresolved Detail": "Lihat rincian",
      "Unresolved Feature Request": "Menunggu Permintaan Fitur",
      "Unresolved Cust Response": "Menunggu Respon Pelanggan",
      "Unresolved Developer Fix": "Menunggu Perbaikan Pengembang",
      "Unresolved Pending": "Tertunda",
      "Tasks Title": "Tugas",
      "Tasks Desc": "Hari ini",
      "Tasks Detail": "Lihat semua",
      "Tasks Create": "Buat tugas baru",
      // Tickets
      "Ticket Title": "Semua tiket",
      "Ticket TH Ticket Detail": "Detail tiket",
      "Ticket TH Cust Name": "Nama Pelanggan",
      "Ticket TH Date": "Tanggal",
      "Ticket TH Priority": "Prioritas",
      "Ticket TD Sub 1": "Diperbarui",
      "Ticket TD Sub 2": "pada",
      "Ticket TD Action 1": "Setujui tiket",
      "Ticket TD Action 2": "Tolak tiket",
      // Settings
      "Settings Theme": "Tema",
      "Theme Light": "Terang",
      "Theme Dark": "Gelap",
      "Theme System": "Sistem",
      "Settings Language": "Bahasa",
      // Table
      "Table Rows Per Page": "Baris per halaman",
      "Table Of": "dari",
      "Table Prev": "Pergi ke halaman sebelumnya",
      "Table Next": "Buka halaman berikutnya",
      "Table Sort": "Sortir",
      "Table Sort Oldest": "Terlama",
      "Table Sort Latest": "Terbaru",
      // Notification
      "Notification Title": "Notifikasi",
      // Search box
      "Search Placeholder": "Cari",
      "Search Not Found": "Tugas tidak ditemukan",
      // Login
      "Login Card Title": "Masuk ke Dashboard Kit",
      "Login Card Desc": "Masukkan email dan kata sandi Anda di bawah ini",
      "Login Form Email": "Alamat email",
      "Login Form Pass": "Kata sandi",
      "Login Form Forgot Pass": "Tidak ingat kata sandi?",
      "Login Register 1": "Belum punya akun?",
      "Login Register 2": "Daftar",
      // Create ticket
      "Ticket Form Title": "Judul",
      "Ticket Form Priority": "Prioritas",
      "Ticket Form Button": "Buat tiket baru",
    },
  },
};
